apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-jenkins-s3-k8s
  namespace: stack-devsecops-k8s
  labels:
    app: jenkins-backup
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        app: jenkins-backup
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: jenkins-backup
              image: abraaojs/k8s-jenkins-s3-backup:v1
              env:
                - name: S3_PATH
                  valueFrom:
                    configMapKeyRef:
                      key: S3_PATH
                      name: aws
                - name: S3_BUCKET
                  valueFrom:
                    secretKeyRef:
                      key: S3_BUCKET
                      name: aws
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: AWS_ACCESS_KEY_ID
                      name: aws
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: AWS_SECRET_ACCESS_KEY
                      name: aws
                - name: BUCKET_REGION
                  valueFrom:
                    secretKeyRef:
                      key: BUCKET_REGION
                      name: aws